In [12]:
import numpy as np
import pandas as pd

In [13]:
def make_df(cols, ind):
    data = {c: [str(c) + str(i) for i in ind]
            for c in cols}
    return pd.DataFrame(data, ind)

class display(object):
    """Display HTML representation of multiple objects"""
    template = """<div style="float: left; padding: 10px;">
    <p style='font-family:"Courier New", Courier, monospace'>{0}</p>{1}
    </div>"""
    def __init__(self, *args):
        self.args = args
        
    def _repr_html_(self):
        rendered = []
        for a in self.args:
            try:
                rendered.append(self.template.format(a, eval(a)._repr_html_()))
            except Exception as e:
                rendered.append(self.template.format(a, f"<pre>Error: {e}</pre>"))
        return '\n'.join(rendered)
    
    def __repr__(self):
        lines = []
        for a in self.args:
            try:
                lines.append(a + '\n' + repr(eval(a)))
            except Exception as e:
                lines.append(f"{a}\nError: {e}")
        return '\n\n'.join(lines)

# Simple concatenation

In [19]:
df1 = make_df('ABC', range(3))
df2 = make_df('DEF', range(3))
display('df1', 'df2', 'pd.concat([df1, df2])', 'pd.concat([df1, df2], axis=1)')

df1
    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

df2
    D   E   F
0  D0  E0  F0
1  D1  E1  F1
2  D2  E2  F2

pd.concat([df1, df2])
     A    B    C    D    E    F
0   A0   B0   C0  NaN  NaN  NaN
1   A1   B1   C1  NaN  NaN  NaN
2   A2   B2   C2  NaN  NaN  NaN
0  NaN  NaN  NaN   D0   E0   F0
1  NaN  NaN  NaN   D1   E1   F1
2  NaN  NaN  NaN   D2   E2   F2

pd.concat([df1, df2], axis=1)
    A   B   C   D   E   F
0  A0  B0  C0  D0  E0  F0
1  A1  B1  C1  D1  E1  F1
2  A2  B2  C2  D2  E2  F2

In [15]:
df3 = make_df('ABC', range(3))
df4 = make_df('DEF', range(3))
display('df3', 'df4', 'pd.concat([df3, df4], axis=1)', 'pd.concat([df3, df4])')

df3
    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

df4
    D   E   F
0  D0  E0  F0
1  D1  E1  F1
2  D2  E2  F2

pd.concat([df3, df4], axis=1)
    A   B   C   D   E   F
0  A0  B0  C0  D0  E0  F0
1  A1  B1  C1  D1  E1  F1
2  A2  B2  C2  D2  E2  F2

pd.concat([df3, df4])
     A    B    C    D    E    F
0   A0   B0   C0  NaN  NaN  NaN
1   A1   B1   C1  NaN  NaN  NaN
2   A2   B2   C2  NaN  NaN  NaN
0  NaN  NaN  NaN   D0   E0   F0
1  NaN  NaN  NaN   D1   E1   F1
2  NaN  NaN  NaN   D2   E2   F2

## duplicate indices

In [16]:
df1 = make_df('ABC', range(3))
df2 = make_df('BCD', range(3))
display('df1', 'df2', 'pd.concat([df1, df2], verify_integrity=True)')

df1
    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

df2
    B   C   D
0  B0  C0  D0
1  B1  C1  D1
2  B2  C2  D2

pd.concat([df1, df2], verify_integrity=True)
Error: Indexes have overlapping values: Index([0, 1, 2], dtype='int64')

In [27]:
df1 = make_df('AB', range(3))
df2 = make_df('CD', range(3))
display('df1', 'df2', 'pd.concat([df1, df2], axis=1, keys=["x", "y"])')

df1
    A   B
0  A0  B0
1  A1  B1
2  A2  B2

df2
    C   D
0  C0  D0
1  C1  D1
2  C2  D2

pd.concat([df1, df2], axis=1, keys=["x", "y"])
    x       y
    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2

## concatenations with joins

In [33]:
df3 = make_df('ABC', range(3))
df4 = make_df('BCD', range(3, 6))
display('df3', 'df4', 'pd.concat([df3, df4])', 'pd.concat([df3, df4], join="inner")', 'pd.concat([df3, df4], join="outer")',
    'pd.concat([df3, df4]).reindex(columns=df3.columns)', 'pd.concat([df3, df4]).reindex(columns=df4.columns)')

df3
    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

df4
    B   C   D
3  B3  C3  D3
4  B4  C4  D4
5  B5  C5  D5

pd.concat([df3, df4])
     A   B   C    D
0   A0  B0  C0  NaN
1   A1  B1  C1  NaN
2   A2  B2  C2  NaN
3  NaN  B3  C3   D3
4  NaN  B4  C4   D4
5  NaN  B5  C5   D5

pd.concat([df3, df4], join="inner")
    B   C
0  B0  C0
1  B1  C1
2  B2  C2
3  B3  C3
4  B4  C4
5  B5  C5

pd.concat([df3, df4], join="outer")
     A   B   C    D
0   A0  B0  C0  NaN
1   A1  B1  C1  NaN
2   A2  B2  C2  NaN
3  NaN  B3  C3   D3
4  NaN  B4  C4   D4
5  NaN  B5  C5   D5

pd.concat([df3, df4]).reindex(columns=df3.columns)
     A   B   C
0   A0  B0  C0
1   A1  B1  C1
2   A2  B2  C2
3  NaN  B3  C3
4  NaN  B4  C4
5  NaN  B5  C5

pd.concat([df3, df4]).reindex(columns=df4.columns)
    B   C    D
0  B0  C0  NaN
1  B1  C1  NaN
2  B2  C2  NaN
3  B3  C3   D3
4  B4  C4   D4
5  B5  C5   D5

## append method
same as simple concat

In [ ]:
df3 = make_df('ABC', range(3))
df4 = make_df('BCD', range(3, 6))
display('df3', 'df4', 'pd.concat([df3, df4])')
df3.a

df3
    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

df4
    B   C   D
3  B3  C3  D3
4  B4  C4  D4
5  B5  C5  D5

pd.concat([df3, df4])
     A   B   C    D
0   A0  B0  C0  NaN
1   A1  B1  C1  NaN
2   A2  B2  C2  NaN
3  NaN  B3  C3   D3
4  NaN  B4  C4   D4
5  NaN  B5  C5   D5